name: error_trace
description: Tools that prevent stack trace loss across async gaps, improving error diagnostics.
version: 1.0.0
repository: https://github.com/ppicas/error_trace
topics:
  - error
  - error-handling
  - stacktrace
  - debug
  - exceptions

environment:
  sdk: ^3.2.0

dependencies:
  stack_trace: ^1.11.1
  meta: ^1.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
