name: error_trace
description: Utilities to preserve stack traces across asynchronous calls for better debugging.
version: 1.0.1
repository: https://github.com/ppicas/error_trace
topics:
  - error
  - error-handling
  - stacktrace
  - debug
  - exceptions

environment:
  sdk: ^3.2.0

dependencies:
  stack_trace: ^1.11.1
  meta: ^1.11.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
